"""Seed demo farms, fields and 150 days of sensor history.

The fields are authored, not randomised. A demo needs to *show* the product's
range within about ninety seconds, so the seed deliberately spans every risk
band and every failure mode the tool is built to catch: a healthy well-drained
plot, a salt-sensitive crop irrigated with brackish water over a shallow water
table, a canal tail-ender that misses turns, and a coastal plot fighting
saltwater intrusion.

History is generated by the physics simulator under synthetic weather rather
than fetched from the network, so seeding works with no connection and produces
identical data every run.
"""
from __future__ import annotations

import logging
from datetime import date, datetime, timedelta, timezone

import numpy as np

from app.database import SessionLocal, init_db
from app.ml.crop_profiles import CROP_SPECS, get_crop
from app.ml.generate import synthetic_weather
from app.ml.physics import FieldState
from app.models import CropProfile, Farm, Field, SensorReading

logger = logging.getLogger(__name__)

HISTORY_DAYS = 150

FARMS = [
    {
        "name": "Sandhu Farms", "owner": "Jaspreet Sandhu",
        "region": "Ludhiana", "state": "Punjab", "lat": 30.9010, "lon": 75.8573,
    },
    {
        "name": "Hisar Agri Collective", "owner": "Ramesh Yadav",
        "region": "Hisar", "state": "Haryana", "lat": 29.1492, "lon": 75.7217,
    },
    {
        "name": "Bhavnagar Coastal Farm", "owner": "Nilesh Patel",
        "region": "Bhavnagar", "state": "Gujarat", "lat": 21.7645, "lon": 72.1519,
    },
]

# (farm_index, name, crop, area, soil, drainage, irrigation EC, water table,
#  initial ECe, irrigation regime, narrative)
FIELDS = [
    (0, "North Block", "wheat", 4.2, "loam", "good", 0.6, 9.0, 1.1, "reliable",
     "Healthy control plot: good drainage, deep water table, canal water."),
    (0, "Canal Side Paddy", "rice", 3.1, "clay", "poor", 2.4, 1.6, 4.2, "reliable",
     "Salt-sensitive rice on brackish tubewell water over a shallow water table."),
    (0, "West Twenty", "wheat", 5.6, "clay_loam", "moderate", 1.4, 3.2, 2.6, "warabandi",
     "Canal tail-ender: turns arrive late, crop runs down between them."),
    (1, "Hisar Cotton A", "cotton", 6.8, "sandy_loam", "moderate", 1.8, 4.5, 3.4, "warabandi",
     "Salt-tolerant cotton holding steady on marginal water."),
    (1, "Village Plot 7", "wheat", 2.4, "clay_loam", "poor", 3.1, 2.0, 5.8, "deficit",
     "Deficit irrigation with saline water - salt is accumulating fast."),
    (1, "Rainfed Strip", "barley", 3.3, "sandy_loam", "good", 0.8, 11.0, 1.6, "rainfed",
     "Unirrigated barley: water-stressed but not salinising."),
    (2, "Coastal Block 1", "cotton", 5.1, "clay", "poor", 4.2, 1.2, 7.9, "reliable",
     "Saltwater intrusion: shallow saline water table near the coast."),
    (2, "Sugarcane East", "sugarcane", 4.7, "clay_loam", "moderate", 2.2, 2.4, 3.0, "reliable",
     "Salt-sensitive sugarcane under moderate salinity pressure."),
    (2, "Reclaimed Plot", "barley", 3.9, "sandy_loam", "good", 1.1, 6.5, 2.8, "reliable",
     "Under reclamation: good drainage is slowly leaching salt out."),
]


def seed_crop_profiles(db) -> None:
    for spec in CROP_SPECS.values():
        if db.get(CropProfile, spec.crop):
            continue
        db.add(CropProfile(
            crop=spec.crop,
            display_name=spec.display_name,
            kc_init=spec.kc_init,
            kc_mid=spec.kc_mid,
            kc_late=spec.kc_late,
            root_depth_m=spec.root_depth_m,
            depletion_fraction=spec.depletion_fraction,
            salt_threshold_a=spec.salt_threshold_a,
            salt_slope_b=spec.salt_slope_b,
            season_days=spec.season_days,
            tolerance_label=spec.tolerance_label,
        ))
    db.commit()


def _irrigation(regime: str, need: float, day: int, state: FieldState,
                rng: np.random.Generator) -> float:
    """Mirror the training generator's supply regimes so seeded history is
    drawn from the same distribution the models were trained on."""
    if regime == "rainfed":
        return 0.0
    if regime == "reliable":
        return need
    if regime == "warabandi":
        if day % 14 != 0 or rng.random() > 0.75:
            return 0.0
        return 65.0
    if regime == "deficit":
        return need * 0.45
    return need


def build_history(field_row: Field, initial_ece: float, regime: str,
                  rng: np.random.Generator) -> list[SensorReading]:
    """Run the physics forward and emit one sensor reading per day."""
    spec = get_crop(field_row.crop)
    state = FieldState(
        crop=field_row.crop,
        soil_texture=field_row.soil_texture,
        drainage_class=field_row.drainage_class,
        root_depth_m=spec.root_depth_m,
        irrigation_water_ec=field_row.irrigation_water_ec,
        water_table_depth_m=field_row.water_table_depth_m,
        groundwater_ec=min(12.0, 2.0 + field_row.irrigation_water_ec * 1.4),
    )
    state.set_initial_ece(initial_ece)

    start = datetime.now(timezone.utc) - timedelta(days=HISTORY_DAYS)
    readings: list[SensorReading] = []

    for day in range(HISTORY_DAYS):
        stamp = start + timedelta(days=day)
        doy = stamp.timetuple().tm_yday
        wx = synthetic_weather(doy, field_row.lat, rng)

        need = state.irrigation_need()
        applied = _irrigation(regime, need, day, state, rng)
        dap = (stamp.date() - field_row.planting_date).days

        res = state.step(
            precip_mm=wx["precip_mm"],
            et0_mm=wx["et0_mm"],
            t_max_c=wx["t_max"],
            days_after_planting=max(0, dap),
            irrigation_mm=applied,
        )

        readings.append(SensorReading(
            field_id=field_row.id,
            ts=stamp,
            soil_ec=round(max(0.05, res.ece + rng.normal(0, 0.08)), 3),
            soil_moisture_pct=round(max(1.0, res.soil_moisture_pct + rng.normal(0, 0.6)), 2),
            soil_temp_c=round(wx["t_mean"] + rng.normal(0, 1.0), 2),
            ph=round(float(np.clip(rng.normal(7.6 + 0.06 * res.ece, 0.25), 5.5, 9.8)), 2),
            irrigation_mm=round(applied, 1),
            source="simulated",
        ))

    return readings


def seed(reset: bool = False) -> None:
    init_db()
    rng = np.random.default_rng(7)

    with SessionLocal() as db:
        if reset:
            for model in (SensorReading, Field, Farm):
                db.query(model).delete()
            db.commit()

        seed_crop_profiles(db)

        if db.query(Farm).count() > 0:
            logger.info("Farms already present; skipping seed. Use reset=True to rebuild.")
            return

        farms = []
        for payload in FARMS:
            farm = Farm(**payload)
            db.add(farm)
            farms.append(farm)
        db.commit()
        for farm in farms:
            db.refresh(farm)

        planting = date.today() - timedelta(days=HISTORY_DAYS - 10)
        created: list[tuple[Field, float, str]] = []

        for (farm_idx, name, crop, area, soil, drainage,
             irr_ec, wt, ece0, regime, _note) in FIELDS:
            farm = farms[farm_idx]
            field_row = Field(
                farm_id=farm.id,
                name=name,
                crop=crop,
                area_ha=area,
                soil_texture=soil,
                drainage_class=drainage,
                planting_date=planting,
                irrigation_water_ec=irr_ec,
                water_table_depth_m=wt,
                # Scatter plots around the farm centroid so the map reads well.
                lat=farm.lat + float(rng.normal(0, 0.012)),
                lon=farm.lon + float(rng.normal(0, 0.012)),
            )
            db.add(field_row)
            created.append((field_row, ece0, regime))
        db.commit()

        total = 0
        for field_row, ece0, regime in created:
            db.refresh(field_row)
            readings = build_history(field_row, ece0, regime, rng)
            db.add_all(readings)
            total += len(readings)
        db.commit()

        print(f"Seeded {len(farms)} farms, {len(created)} fields, {total:,} sensor readings")
        for field_row, ece0, regime in created:
            latest = max(
                (r for r in db.query(SensorReading)
                 .filter(SensorReading.field_id == field_row.id).all()),
                key=lambda r: r.ts,
            )
            print(f"  {field_row.name:<20} {field_row.crop:<10} "
                  f"ECe {ece0:>5.1f} -> {latest.soil_ec:>5.2f}  ({regime})")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Seed the demo database.")
    parser.add_argument("--reset", action="store_true", help="Wipe existing data first.")
    args = parser.parse_args()
    seed(reset=args.reset)
